### ISSUE TITLE
Your First Component 

### ISSUE THREAD

**Issue by g-savitha** [reactjs/te.react.dev#21]
URL - https://te-react-dev.vercel.app/learn/your-first-component
Requires modification to [src/content/learn/your-first-component.md](https://github.com/reactjs/te.react.dev/tree/main/src/content/learn/your-first-component.md) this file.

If you want to translate this page, please comment below so I can assign you.

**Comment by g-savitha** [comment]
@v891 Please check the glossary and discussions page for more info.

**Comment by Shiva-Sai-ssb** [comment]
Hi @srikanth-kandi, I would like to work on this issue. Could you assign it to me?
