### ISSUE TITLE
Importing and Exporting Components

### ISSUE THREAD

**Issue by g-savitha** [reactjs/te.react.dev#36]
URL - https://te-react-dev.vercel.app/learn/importing-and-exporting-components
Requires modification to [src/content/learn/importing-and-exporting-components.md](https://github.com/reactjs/te.react.dev/tree/main/src/content/learn/importing-and-exporting-components.md) this file.

If you want to translate this page, please comment below so I can assign you.

**Comment by Shiva-Sai-ssb** [comment]
Hi @srikanth-kandi, I want to work on this. Kindly assign the issue to me.
