### ISSUE TITLE
Thinking in React

### ISSUE THREAD

**Issue by g-savitha** [reactjs/te.react.dev#8]
URL - https://te-react-dev.vercel.app/learn/thinking-in-react
Requires modification to [src/content/learn/thinking-in-react.md](https://github.com/reactjs/te.react.dev/tree/main/src/content/learn/thinking-in-react.md) this file.

If you want to translate this page, please comment below so I can assign you.

**Comment by srikanth-kandi** [comment]
Hi @g-savitha are you still working on this issue?
