### ISSUE TITLE
Using TypeScript

### ISSUE THREAD

**Issue by srikanth-kandi** [reactjs/te.react.dev#99]
URL - [https://te-react-dev.vercel.app/learn/typescript](https://te-react-dev.vercel.app/learn/typescript)
Requires modification to [src/content/learn/typescript.md](https://github.com/reactjs/te.react.dev/tree/main/src/content/learn/typescript.md) this file.

If you want to translate this page, please comment below so I can assign you.

**Comment by shajahanshaik915** [comment]
Hi, I’d like to work on translating the ‘Using TypeScript’ page into Telugu. Please assign this issue to me. Thanks!

**Comment by srikanth-kandi** [comment]
Hello @shajahanshaik915, Thanks for showing interest in contributing to the translation of React to Telugu. Please follow the [glossary](https://github.com/reactjs/te.react.dev/issues/13
). Also, please look at the already translated content mentioned in issue 1.

**Comment by shajahanshaik915** [comment]
Hello @srikanth-kandi, I've raised a PR here https://github.com/reactjs/te.react.dev/pull/116, Can you please review this and let me know if changes are required.
